### ISSUE TITLE
xst not found

### ISSUE THREAD

**Issue by FrederickGeek8** [teknohog/Xilinx-Serial-Miner#1]
When I try to make the program, it says that it cannot find xst. Now I have downloaded the Xilinx ISE Design Suite installer (I assumed that is what I should do), and I am presented by an edition list. Which one should I install? My option are:

<pre>
ISE WebPACK
ISE Design Suite Login Edition + Vivado Design Edition
ISE Design Suite Embedded Edition + Vivado Design Edition
ISE Design Suite DSP Edition + Vivado Design Edition
ISE Design Suite System Edition + Vivado Design Edition
Software Developement Kit - Standalone Installation
Lab Tools - Standalone Installation
Xilinx Documentation Navigator - Standalone Installation
</pre>

**Comment by teknohog** [comment]
WebPACK is probably the only version you can use without buying a license.

However, there are a few general things here. First of all, I don't work on this project any more. My more recent work on FPGA miners are found in the other project (Open source FPGA bitcoin miner), but even that is not actively maintained. Day job, other interests and all that...

Also, the make script was provided by Saar Drimer and his boldport tools. I don't currently use them.

I don't mean to sound patronizing or anything, but if you didn't have a working knowledge of Xilinx ISE before, you probably shouldn't dive into a project like this, but learn some FPGA basics first.

**Comment by FrederickGeek8** [comment]
I really just want to get this thing running and leave it running for a while. I don't really see my self using the FPGA for anything else; I was surprised I even had one.

I was interested in this project because you had the same chip that I have (Spartan 3E 500K), so if you recommend I use a different miner I'll try it out... I just want something that supports my FPGA
